apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-q5tm
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-q5tm
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-q5tm
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-q5tm
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-q5tm
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-lkhj-tenant/rhtap-demo-app/hacbs-test-project-q5tm@sha256:3da6d0515f0284fc3dc3942cba2808506528e01c43d9d7c7526ea7e61840ca74
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
